version: "3.8"
services:

  backend:
    build:
      context:
        backend
      dockerfile:
        Dockerfile
    image: backend/{{cookiecutter.backend_image_name}}:local
    ports:
      - {{cookiecutter.backend_port}}:{{cookiecutter.backend_port}}

  frontend:
    build:
      context:
        frontend
      dockerfile:
        Dockerfile
    image: frontend/{{cookiecutter.frontend_image_name}}:local
    ports:
      - {{cookiecutter.frontend_port}}:{{cookiecutter.frontend_port}}
