version: "3.8"
services:

  {{cookiecutter.backend_name}}:
    build:
      context:
        {{cookiecutter.backend_name}}
      dockerfile:
        Dockerfile
    image: {{cookiecutter.backend_name}}/{{cookiecutter.backend_image_name}}:local
    ports:
      - {{cookiecutter.backend_port}}:{{cookiecutter.backend_port}}

  {{cookiecutter.frontend_name}}:
    build:
      context:
        {{cookiecutter.frontend_name}}
      dockerfile:
        Dockerfile
      args:
        - REACT_APP_{{cookiecutter.backend_name|upper}}_ADDRESS="http://localhost:{{cookiecutter.backend_port}}"
    image: {{cookiecutter.frontend_name}}/{{cookiecutter.frontend_image_name}}:local
    ports:
      - {{cookiecutter.frontend_port}}:{{cookiecutter.frontend_port}}
