replicaCount: 1

image:
  repository: {{cookiecutter.frontend_name}}
  tag: "{{cookiecutter.dev_image_tag}}"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: {{cookiecutter.frontend_port}}

config:
  {{cookiecutter.backend_name}}_host: "http://localhost"
  {{cookiecutter.backend_name}}_port: {{cookiecutter.backend_port}}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
