version: "3.8"
services:

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:{{ cookiecutter.redis_port }}

  database:
    image: postgres:15-alpine
    expose:
      - {{ cookiecutter.postgres_port }}
    volumes:
      - /tmp/{{ cookiecutter.postgres_database }}:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER={{ cookiecutter.postgres_username }}
      - POSTGRES_PASSWORD={{ cookiecutter.postgres_password }}
      - POSTGRES_DB={{ cookiecutter.postgres_database }}

  backend:
    build:
      context:
        backend
      dockerfile:
        Dockerfile
    image: python/backend
    command: uvicorn api:api --host 0.0.0.0 --port 5000
    ports:
      - 5000:{{ cookiecutter.backend_port }}
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://{{ cookiecutter.postgres_username }}:{{ cookiecutter.postgres_password }}@database:{{ cookiecutter.postgres_port }}/{{ cookiecutter.postgres_database }}
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0

  worker:
    build:
      context:
        backend
      dockerfile:
        Dockerfile
    image: python/worker
    command: celery -A worker.tasks worker --loglevel=INFO
    depends_on:
      - redis
      - backend
    environment:
      - DATABASE_URL=postgresql://{{ cookiecutter.postgres_username }}:{{ cookiecutter.postgres_password }}@database:{{ cookiecutter.postgres_port }}/{{ cookiecutter.postgres_database }}
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0

  frontend:
    build:
      context:
        frontend
      dockerfile:
        Dockerfile
    image: node/frontend
    command: npm run start
    ports:
      - 3000:{{ cookiecutter.frontend_port }}
    depends_on:
      - backend
