apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-template
spec:
  templates:

  - name: create-build-template
    inputs:
      parameters:
      - name: # ...
    # ...  

  - name: upload-build-template
    inputs:
      parameters:
      - name: # ...
    # ...  
