name: Backend Unit Test (dev)

on:
  push:
    branches:
      - {{cookiecutter.dev_branch}}
    paths:
      - backend/**
  pull-request:
    branches:
      - {{cookiecutter.dev_branch}}
    paths:
      - backend/**

jobs:
  backend-unit-test:
    name: "Unit test the backend changes on dev"
    runs-on: ubuntu-latest

    steps:
      - id: backend-unit-test-checkout
        name: "Checkout repository"
        uses: actions/checkout@v3
      
      - id: backend-unit-test-setup
        name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: {{cookiecutter.backend_python_version}}
      
      - id: backend-unit-test-install
        name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
      
      - id: backend-unit-test-run
        name: "Run unit tests"
        run: |
          python -m pytest backend/tests -svv
        env:
          CI: true
