name: Breaking Changes Check

on:
  pull_request:
    branches:
      - {{cookiecutter.dev_branch}}
      - {{cookiecutter.prod_branch}}

jobs:
  breaking-changes-check:
    name: "Check for breaking changes"
    runs-on: ubuntu-latest

    steps:
      - id: breaking-changes-check-checkout
        name: "Checkout repository"
        uses: actions/checkout@v3
      
      - id: breaking-changes-check-list
        name: "List the changed files"
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:base
          git diff --name-only base...${{ github.sha }} > changed_files.txt
          echo "changed-files=$(cat changed_files.txt)" >> $GITHUB_ENV

      - id: breaking-changes-check-subfolders
        name: "Check for changes in subfolders"
        run: |
          CHANGED_FILES=$(echo ${{ env.changed-files }})
          SERVICES_CHANGED=false
          INFRASTRUCTURE_CHANGED=false

          for file in $CHANGED_FILES; do
            if [[ $file == {{cookiecutter.backend_name}}/* ]]; then
              SERVICES_CHANGED=true
            fi
            if [[ $file == {{cookiecutter.frontend_name}}/* ]]; then
              SERVICES_CHANGED=true
            fi
            if [[ $file == infrastructure/* ]]; then
              if [[ $file != infrastructure/local/* ]]; then
                INFRASTRUCTURE_CHANGED=true
              fi
            fi 
          done

          echo "services-changed=$SERVICES_CHANGED" >> $GITHUB_ENV
          echo "infrastructure-changed=$INFRASTRUCTURE_CHANGED" >> $GITHUB_ENV

      - id: breaking-changes-check-output
        name: "Output warning if applicable"
        if: env.services-changed == 'true' && env.infrastructure-changed == 'true'
          run: |
            echo "### Warning :warning:" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "This pull request contains changes from the services and infrastructure subfolders." >> $GITHUB_STEP_SUMMARY
            echo "This could introduce breaking changes if the services deploy before the infrastructure has finished executing." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please confirm this PR does not include breaking changes before merging." >> $GITHUB_STEP_SUMMARY
            echo "If there are, refactor this PR into two separate PRs (merging the infrastructure changes first)" >> $GITHUB_STEP_SUMMARY

