name: Cloud Plan infrastructure

on:
  pull_request:
    branches:
      - {{cookiecutter.dev_branch}}
      - {{cookiecutter.prod_branch}}
    paths:
      - infrastructure/cloud/**

jobs:
  cloud-plan-infrastructure:
    name: "Plan the Cloud changes"
    runs-on: ubuntu-latest
    environment: ${{ "{{" }} github.base_ref {{ "}}" }}

    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - id: cloud-plan-infrastructure-checkout
        name: "Checkout repository"
        uses: actions/checkout@v3
      
      - id: cloud-plan-infrastructure-environment
        name: "Set environment variables"
        run: |
          echo "TF_WORKSPACE={{cookiecutter.tf_cloud_workspace}}" >> $GITHUB_ENV
          echo "TF_LOCAL_DIRECTORY=infrastructure/cloud/." >> $GITHUB_ENV
          echo "TF_CLOUD_ORGANIZATION={{cookiecutter.tf_cloud_organization}}" >> $GITHUB_ENV
          echo "TF_API_TOKEN={{ "${{" }} secrets.TF_TOKEN {{ "}}" }}" >> $GITHUB_ENV
      
      - id: cloud-plan-infrastructure-upload
        name: "Upload config to Terraform Cloud"
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        with:
          workspace: "{{cookiecutter.tf_cloud_workspace}}"
          directory: "infrastructure/cloud/."
          speculative: true

      - id: cloud-plan-infrastructure-create
        name: "Create Terraform plan"
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        with:
          workspace: "{{cookiecutter.tf_cloud_workspace}}"
          configuration_version: "{{ "${{" }} steps.cloud-plan-infrastructure-upload.outputs.configuration_version_id {{ "}}" }}"
          plan_only: true

      - id: cloud-plan-infrastructure-plan
        name: "Plan Terraform changes"
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        with:
          plan: "{{ "${{" }} fromJSON(steps.cloud-plan-infrastructure-create.outputs.payload).data.relationships.plan.data.id {{ "}}" }}"
        env:
          TF_VAR_project_id={{ "${{" }} secrets.GCP_PROJECT_ID {{ "}}" }}
          TF_VAR_image_tag={{ "${{" }} vars.IMAGE_TAG {{ "}}" }}
    
      - id: cloud-plan-infrastructure-pr
        name: "Update PR with planned Terraform changes"
        uses: actions/github-script@v6
        with:
          github-token: {{ "${{" }} secrets.GITHUB_TOKEN {{ "}}" }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
            });
            const botComment = comments.find(comment => {
                return comment.user.type === 'Bot' && comment.body.includes('Terraform Cloud Plan Output')
            });
            const output = `#### Terraform Cloud Plan Output
                \`\`\`
                Plan: {{ "${{" }} steps.cloud-plan-infrastructure-plan.outputs.add {{ "}}" }} to add, {{ "${{" }} steps.cloud-plan-infrastructure-plan.outputs.change {{ "}}" }} to change, {{ "${{" }} steps.cloud-plan-infrastructure-plan.outputs.destroy {{ "}}" }} to destroy.
                \`\`\`
                [Terraform Cloud Plan]({{ "${{" }} steps.cloud-plan-infrastructure-create.outputs.run_link {{ "}}" }})
                `;
            // 3. Delete previous comment so PR timeline makes sense
            if (botComment) {
                github.rest.issues.deleteComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: botComment.id,
                });
            }
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
            });
